### ISSUE TITLE
Fix how special page is loaded

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticComments#16]
`Deprecated: Use of Array syntax for $wgSpecialPages is deprecated (CECommentSpecial), define a subclass of SpecialPage instead. was deprecated in MediaWiki 1.18. [Called from SpecialPageFactory::getUsablePages in /vagrant/mediawiki/includes/specialpage/SpecialPageFactory.php at line 439] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 309`

**Comment by kghbln** [comment]
This extension was abandoned. See https://github.com/SemanticMediaWiki/SemanticComments/issues/25 for further details and an alternative.
