### ISSUE TITLE
Merge old PRs

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticComments#2]
- [x] #11 ( https://github.com/wikimedia/mediawiki-extensions-SemanticComments/pull/1 )
- [x] #7 ( https://github.com/wikimedia/mediawiki-extensions-SemanticComments/pull/2 )

**Comment by mwjames** [comment]
So you cherry pick them and repost them to this repository, I guess, or?

**Comment by kghbln** [comment]
> wikimedia/mediawiki-extensions-SemanticComments#1
wikimedia/mediawiki-extensions-SemanticComments#2

I believe that we well all do us a favour if these commiats are being tagged as 2.0.0 Currently there are several versions around calling themselves 1.0. Thus things will be finally identifiably. At the same time SC should start adopting semver. That's why I wrote 2.0.0 instead of 2.0

**Comment by kghbln** [comment]
@PeterTheOne [FYI](https://phabricator.wikimedia.org/T186878#3960764)

**Comment by PeterTheOne** [comment]
@kghbln PRs are "moved". Old Repository can be closed.

**Comment by kghbln** [comment]
@PeterTheOne Thanks for the note. You should be able to merge yourself.

**Comment by kghbln** [comment]
@PeterTheOne Will be there a designated tag for MW 1.27 or will the fix for PHP 7 and MW 1.31 also work for MW 1.27?

**Comment by PeterTheOne** [comment]
It should with MW 1.27, the first part of the PR was a fix I did for 1.27 in October. Now I tested and fixed for MW 1.31 and PHP 7

**Comment by kghbln** [comment]
Thanks for the info!

**Comment by PeterTheOne** [comment]
Testing with travis on multiple versions would be nice ^^

**Comment by kghbln** [comment]
> Testing with travis on multiple versions would be nice ^^

Indeed. I'd say go for it. :) Worth to open an issue about it in any case.
