### ISSUE TITLE
Cancel-button missing

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticComments#21]
The "cancel" button ("Abbrechen" in the example). Does not work. There is only the text "Abbrechen" without any button functionality.

![grafik](https://user-images.githubusercontent.com/4318745/37918452-5d35e186-3121-11e8-8373-47dc0dc433e5.png)

**Comment by PeterTheOne** [comment]
But does clicking cancel work?
https://github.com/SemanticMediaWiki/SemanticComments/blob/9aee4498ab518253ab2c6bf3500786f5e2560c66/scripts/Comment/CE_Comment.js#L479-L485

**Comment by krabina** [comment]
no. It does not have to be a button, but the result currently is onyl the text that is not clickable

**Comment by PeterTheOne** [comment]
Any javascript errors in the browser console?

**Comment by krabina** [comment]
No errors. This is the resulting HTML:
![grafik](https://user-images.githubusercontent.com/4318745/37959923-93d2d1ac-31b4-11e8-91c7-352aaa97d034.png)

**Comment by PeterTheOne** [comment]
Works for me in chromium:

![sc-cancel](https://user-images.githubusercontent.com/666289/38777376-16925f58-40a7-11e8-97d7-40be0d3dbada.gif)

**Comment by PeterTheOne** [comment]
@krabina What happens when you enter `ceCommentForm.formReset();` into the console, with the add comment open?
Also which browser are you using?

**Comment by krabina** [comment]
Pulled the latest master version (just to make sure), used Crome Version 65.0.3325.181  - same thing. When I enter the ceCommentForm.formReset(); than it closes the edit window as expected.

The problem is that the "Cancel" is not blue but grey and therefore is no link...

**Comment by krabina** [comment]
In the HTML above,  the "Abbrechen" should be inside the span tag. Wen I do that manually it works. 

Mut be here somehwere: https://github.com/SemanticMediaWiki/SemanticComments/blob/9aee4498ab518253ab2c6bf3500786f5e2560c66/scripts/Comment/CE_Comment.js#L479-L485

**Comment by PeterTheOne** [comment]
You are right, ` | Abbrechen` should be in the span. `CE_Coment.js` looks fine.

Is the html  of the site otherwise valid ( https://validator.w3.org/ )?

**Comment by kghbln** [comment]
This extension was abandoned. See https://github.com/SemanticMediaWiki/SemanticComments/issues/25 for further details and an alternative.
