### ISSUE TITLE
File Attachments not recognized

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticComments#22]
In the "attach" field one can attach a wiki article (because no wikitext is possible in comments).

If you enter "File:Some-Name.pdf" as article to be attached, a redlink to a page "File-Some-Name.pdf" ist displayed, however when clicked it does not lead to an upload-dialoge, but instead would create a page with that name.

It should do the same that happens when you add [[File:Some-Name.pdf]] to an arbitrary wiki page: display a red link that wen clicke on leads to an upload dialogue.

**Comment by krabina** [comment]
It seems that the "file upload" functionality was intended to to attachments, not attach wiki pages?

https://github.com/SemanticMediaWiki/SemanticComments/blob/9aee4498ab518253ab2c6bf3500786f5e2560c66/specials/Comment/CE_CommentParserFunctions.php#L285-L310

Anyway, no upload dialog is shown.

**Comment by PeterTheOne** [comment]
When I open the Comment directly (`Comment:[...]`) then the link works as expected, but when the comment is displayed elsewhere it fails just as you described.

**Comment by PeterTheOne** [comment]
I narrowed it down to `arraymapce` https://github.com/SemanticMediaWiki/SemanticComments/blob/9aee4498ab518253ab2c6bf3500786f5e2560c66/specials/Comment/CE_CommentParserFunctions.php#L445-L485
which is a copy(?) of PageForms' `arraymap`

https://github.com/wikimedia/mediawiki-extensions-PageForms/blob/d495d9f1603230cc928dcf69effa9b69e566745b/includes/PF_ParserFunctions.php#L390-L433

which also has a `arraymaptemplate`

https://github.com/wikimedia/mediawiki-extensions-PageForms/blob/d495d9f1603230cc928dcf69effa9b69e566745b/includes/PF_ParserFunctions.php#L435-L477
.
See also https://www.mediawiki.org/wiki/Extension:Page_Forms/Page_Forms_and_templates

**Comment by PeterTheOne** [comment]
Ok, I think I know whats going on: when linking to a **file description page** you would use `[[:File:somefile.jpg]]` instead of `[[File:somefile.jpg]]` (Which would display the file directly). But then again if the files doesn't exist this doesn't link to the file upload page but to the dialog of creating a new page.

**Comment by PeterTheOne** [comment]
I tried
`{{#arraymapce:{{{10|}}}|,|x|{{#ifexist: x|[[:x]]|[x]}}|&nbsp;}}`
instead of
`{{#arraymapce:{{{10|}}}|,|x|[[:x]]|[x]|&nbsp;}}`
within `Template:CommentResult`, which doesn't seem to work (Because of arraymapce, I guess).
`{{#ifexist:{{{10|}}}|[[:{{{10|}}}]]|[[{{{10|}}}]]}}` works without `arraymapce`, but only for one attachment and not multiple.

**Comment by PeterTheOne** [comment]
One solution would be to implement `arraymaptemplate` https://www.mediawiki.org/wiki/Extension:Page_Forms/Page_Forms_and_templates#arraymaptemplate for SC and use the ifexists in `arraymaptemplate`.

**Comment by PeterTheOne** [comment]
Ok, I found a way to make it work:

- Install Extension Page Forms.
- Create a template: `Template:AttachedArticle`: `{{#ifexist:{{{1|}}}|[[:{{{1|}}}]]|[[{{{1|}}}]]}}`
- Change `Template:CommentResult` attached articles to: `{{#arraymaptemplate:{{{10|}}}|AttachedArticle|,|&nbsp;}}`

**Comment by mwjames** [comment]
> Install Extension Page Forms.

Are you proposing to make PF a hard dependency for SemanticComments in order to support this feature? Not sure I like the idea. Can you disable that part and only enable it in case PF is available?

**Comment by PeterTheOne** [comment]
@mwjames No, I wouldn't want that. Maybe do as you said or try to copy that function.

**Comment by kghbln** [comment]
This extension was abandoned. See https://github.com/SemanticMediaWiki/SemanticComments/issues/25 for further details and an alternative.
