### ISSUE TITLE
Officially abandon Semantic Comments?

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticComments#25]
@krabina I believe to remember that we talked about this extension in Regensburg in December.

If I understood correctly the [CommentStreams extension](https://www.mediawiki.org/wiki/Extension:CommentStreams) with it's support for Semantic MediaWiki does exactly what this extension is trying to achieve but in an even better way. Thus SemanticComments developent may be stopped. Note that I am not claiming that it really picked up momentum in the past when looking at the current open issues and that not even a 2.0 was tagged at some point.

**Comment by krabina** [comment]
yes, it was a bad timing. Currently, CommentStreams can do everything that is required for my usecases and is better maintained. So I don't have any plans to futher support Semantic Comments, I will try to migrate everything where I need this to CommentStreams....

**Comment by kghbln** [comment]
> yes, it was a bad timing

Indeed, but sometimes things like that happen. 

> So I don't have any plans to futher support Semantic Comments, I will try to migrate everything where I need this to CommentStreams....

Since you were the last supporter of this extension when it comes to getting changes in I believe it is best to abandon and inform potential users about this. The code is still available so if some time in the future a developer wants to pick up support for this extension in a serious way it can still be done without having to start from scratch.

**Comment by kghbln** [comment]
Closed per #26
