### ISSUE TITLE
Don't hardcode property names!

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticComments#5]
Things like `array($comNS . ":" . $pageName, "?Has comment date"),` shouldn't be found in a class, this isn't a user input!

https://github.com/SemanticMediaWiki/SemanticComments/blob/656c39acbfa39e064dd229ed558a917dc1057821/specials/Comment/CE_Comment.php#L96-L103

**Comment by kghbln** [comment]
Related to https://github.com/SemanticMediaWiki/SemanticComments/issues/1. Currently this extension does not support I18n at all.

**Comment by kghbln** [comment]
This extension was abandoned. See https://github.com/SemanticMediaWiki/SemanticComments/issues/25 for further details and an alternative.
