### ISSUE TITLE
Avoid arbitrary Store::updateData requests 

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticComments#6]
We normally do not send arbitrary `Store::updateData` requests (since we update in deferred mode), so this requires a review whether it is really necessary or not and doesn't override any data in the store by accident.

https://github.com/SemanticMediaWiki/SemanticComments/blob/656c39acbfa39e064dd229ed558a917dc1057821/specials/Comment/CE_Comment.php#L154-L166

**Comment by kghbln** [comment]
This extension was abandoned. See https://github.com/SemanticMediaWiki/SemanticComments/issues/25 for further details and an alternative.
